name: Publish Golang Trending Repos to Nostr

on:
  schedule:
    # Publish to Nostr twice a day
    # 11 AM CST
    - cron:  '0 16 * * *'

jobs:
  publish_to_nostr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Publish to Nostr 
        env:
          NOSTR_HEX_SK: ${{ secrets.NOSTR_HEX_SK }}
          REDIS_URI: ${{ secrets.REDIS_URI }}
        run: go run main.go nostr
