name: Publish Golang Trending Repos to Nostr

on:
  schedule:
    # Publish to Nostr twice a day
    # 9 AM CST
    # 9 PM CST
    - cron:  '0 2,14 * * *'

jobs:
  publish_to_nostr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Publish to Nostr 
        run: go run main.go nostr
