name: Test GitHub inspector 

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Test
        run: go test -v ./...
        env:
          REDIS_ADDR: localhost:6379
          REDIS_PASSWORD: ""
